// src/components/BodyPart/AllDishes/ItemBlock/index.tsx
import { CatFood, CatFoodCan, Fish } from '../PriceImg'
import { createMemo } from 'solid-js'

import catFood from '@/assets/catFood.svg'
import catFoodCan from '@/assets/catFoodCan.svg'
import timer from '@/assets/timer.svg'
import type { Item } from '@/menu/menuTypes'
import { cartAddOne } from '@/states'

import css from './index.module.scss'

export default (props: { item: Item }) => {
  const imgSrc = createMemo(() =>
    new TextEncoder().encode(props.item.cnName).reduce((a, b) => a + b, 0) % 2
      ? catFood
      : catFoodCan
  )
  const priceJsx = createMemo(() => {
    const { price } = props.item
    return (
      <>
        {' '}
        {price[0] > 0 && <CatFood price={price[0]} />}
        {(price[0] > 0 || price[1] > 0) && <CatFoodCan price={price[1]} />}
        <Fish price={price[2]} />
      </>
    )
  })
  const durText = createMemo(() => {
    const dur = props.item.durMin
    const durHour = `0${Math.floor(dur / 60)}`.slice(-2)
    const durMin = `0${Math.floor(dur % 60)}`.slice(-2)
    return `${durHour}:${durMin}`
  })

  return (
    <button
      type='button'
      class={css.itemBlockBtn}
      // class="h-34 w-full p-3 my-1 flex shadow-y-lg rounded-xl
      // hover:bg-gray-200 transition-all duration-800 ease-out" :class="[darkBgBigOColor]"
      onClick={() => {
        cartAddOne(props.item)
      }}
    >
      <div class={css.itemBlockBtnContent}>
        {/* Image */}
        <img
          class={css.itemImg}
          src={imgSrc()}
          // class="h-full p-5 aspect-square self-center bg-white
          // dark:(filter invert) rounded-3xl shadow-md"
        />

        {/* Detail */}
        <span
        // class="w-full h-full ml-5 flex flex-col items-start whitespace-nowrap overflow-hidden"
        >
          {/* Title */}
          <b
          // class="my-1 text-lg text-shadow"
          >
            {props.item.cnName}
          </b>

          {/* Category & chefs */}
          <span
          // class="flex-grow overflow-hidden overflow-ellipsis"
          // :class="secondaryTextColor"
          >
            {props.item.category.cnName} | {props.item.chefs.join(' · ')}
          </span>

          {/* Time & Price */}
          <span
          // class="h-6 w-full flex justify-between"
          >
            {/* Time */}
            <span
            // class="flex flex-center"
            >
              <img
                // class="h-5 pr-0.5" :
                src={timer}
              />
              {durText()}
            </span>

            {/* Price */}
            <span
            //  class="max-h-full flex"
            >
              {priceJsx()}
            </span>
          </span>
        </span>
      </div>
    </button>
  )
}

// src/components/AllDishes/ItemBlock.vue
<script setup lang="ts">
import fish from '@/assets/fish.svg'
import catFood from '@/assets/catFood.svg'
import catFoodCan from '@/assets/catFoodCan.svg'
import { darkBgBigOColor } from '@/utils/colors'
import type { Item } from '@/menu/menu_types'
import PriceImg from './PriceImg.vue'

const props = defineProps<{ item: Item }>()

const secondaryTextColor = ['text-gray-500', 'dark:text-gray-300']

const getRandPrice = () => Math.floor(Math.random() * 200) + 5

let x = getRandPrice()
const price: [number, number, number] = [Math.floor(x / 100), 0, 0]
x %= 100
price[1] = Math.floor(x / 10)
x %= 10
price[2] = x
</script>






<template>
  <div class="h-32 p-2 my-3 rounded-xl flex flex-col justify-center bg-gray-300 shadow-md" :class="[darkBgBigOColor]">
    <!-- Item & Image -->
    <span class="flex">
      <!-- Item -->
      <span class='ml-2 w-full flex flex-col justify-center whitespace-nowrap overflow-hidden'>
        <!-- Title -->
        <b class="my-1 text-lg text-shadow">{{ props.item.cnName }}</b>
        <!-- Category -->
        <span class="overflow-hidden overflow-ellipsis"
          :class="secondaryTextColor">{{ props.item.category.cnName }}</span>
        <!-- Chefs -->
        <span class="overflow-hidden overflow-ellipsis"
          :class="secondaryTextColor">{{ props.item.chefs.join(' · ') }}</span>
      </span>

      <!-- Image -->
      <img :src='Math.random() > 0.5 ? catFood : catFoodCan'
        class="max-w-[7vh] max-h-full p-1 aspect-square self-center dark:invert">
    </span>

    <!-- Price -->
    <span class="h-6 mt-2 self-end">
      <PriceImg :price="price[0]" :src="catFood" v-if="price[0] > 0" />
      <PriceImg :price="price[1]" :src="catFoodCan" v-if="price[0] > 0 || price[1] > 0" />
      <PriceImg :price="price[2]" :src="fish" />
    </span>
  </div>
</template>
